### ISSUE TITLE
Nullable array items

### ISSUE THREAD

**Issue by adborden** [chaijs/Chai-Things#18]
Trying to assert my array contains at least one null item, but I'm not sure if I'm using the library correctly. I can't seem to find a way to write it. The simple test case:

```coffeescript
describe "nullable array items", ->
  array = ['a', 'b', null]

  it "should include something null", ->
    array.should.include.something.null
```

Fails with:
```
  1) nullable array items should include something null:
     expected null to be null
```

I've tried writing this in various ways, but I get similar errors:
```coffeescript
expect(array).not.all.to.exist # AssertionError: expected null to not exist
```

**Comment by keithamus** [comment]
Hey @adborden thanks for the issue.

I'm not sure you need Chai-Things for this particular assertion, as this can be handled with chai plain:

```js
expect([1,2,null]).to.include(null);
```

I'm going to close this issue - assuming that the above assertion is what you want. If it's not please let me know and I'll re-open it right away :smile:
